---
apiVersion: v1
kind: Namespace
metadata:
   name: {{ .Values.namespace }}
---
apiVersion: v1
kind: Pod
metadata:
  name: warden
  labels:
    app: warden
  namespace: {{ .Values.namespace }}
spec:
  restartPolicy: OnFailure
  containers:
    - name: warden
      image: {{ .Values.image_name }}:{{ .Values.ver_num }} #EXAMPLE-USE YOUR IMAGE REPO/IMAGE
      imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: warden
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: warden
  ports:
  - port: 443
    targetPort: 443
